services:
  docs:
    image: rs_blackmarket_local_docs
    container_name: rs_blackmarket_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./rs_blackmarket:/app/rs_blackmarket:z
    ports:
      - '9000:9000'
    command: /start-docs
